import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:crypto/crypto.dart';
import '../model/news_item.dart';
import 'DatabaseHelper.dart';

class ApiService {
  static const String apiKey = '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';
  static const String endpoint = 'https://api.openai.com/v1/chat/completions';
  final DatabaseHelper dbHelper;

  ApiService(this.dbHelper);

  Future<List<NewsItem>> fetchScienceNews() async {
    final cachedTimestamp = await dbHelper.getTimestamp('scienceNewsTimestamp');
    if (cachedTimestamp != null) {
      final lastCached = DateTime.parse(cachedTimestamp);
      final now = DateTime.now();
      if (lastCached.day == now.day &&
          lastCached.month == now.month &&
          lastCached.year == now.year) {
        return await dbHelper.getNewsItems();
      }
    }

    final response = await http.post(
      Uri.parse(endpoint),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $apiKey',
      },
      body: jsonEncode({
        'model': 'gpt-3.5-turbo',
        'messages': [
          {
            'role': 'user',
            'content':
            'Provide a list of recent science events, discoveries, or findings from Nigeria. Include title, summary, date, source, sourceUrl and details for each. Format as JSON.'
          }
        ],
      }),
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      final newsJson = jsonDecode(data['choices'][0]['message']['content']);
      final newsItems = (newsJson as List).map((item) => NewsItem(
        title: item['title']?.toString() ?? '',
        summary: item['summary']?.toString() ?? '',
        details: item['details']?.toString() ?? '',
        sourceUrl: item['sourceUrl']?.toString() ?? '',
        source: item['source']?.toString() ?? '',
        date: item['date']?.toString() ?? '',
        responseType: 'news',
      )).toList();

      await dbHelper.insertNewsItems(newsItems);
      await dbHelper.saveTimestamp('scienceNewsTimestamp', DateTime.now().toIso8601String());
      return newsItems;
    } else {
      throw Exception('Failed to fetch news');
    }
  }

  Future<NewsItem> answerPrompt(String prompt) async {
    final responseKey = 'prompt_${md5.convert(utf8.encode(prompt)).toString()}';
    final response = await http.post(
      Uri.parse(endpoint),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $apiKey',
      },
      body: jsonEncode({
        'model': 'gpt-3.5-turbo',
        'messages': [
          {
            'role': 'user',
            'content':
            'Provide information about scientific methods related to the topic: "$prompt", prioritizing Nigerian research or context if available, otherwise provide global scientific information. Format the response as a JSON object with fields: "title" (a brief title for the method or finding), "summary" (a brief description), "details" (detailed explanation), "source" (source or "Generated by AI" if none), "sourceUrl" (URL or empty string if none), and "date" (date of the finding or current date in YYYY-MM-DD format).'
          }
        ],
      }),
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      final item = jsonDecode(data['choices'][0]['message']['content']);
      final newsItem = NewsItem(
        title: item['title']?.toString() ?? '',
        summary: item['summary']?.toString() ?? '',
        details: item['details']?.toString() ?? '',
        sourceUrl: item['sourceUrl']?.toString() ?? '',
        source: item['source']?.toString() ?? 'Generated by AI',
        date: item['date']?.toString() ?? DateTime.now().toIso8601String().split('T')[0],
        responseType: 'method',
      );

      await dbHelper.insertPromptResponse(responseKey, newsItem);
      return newsItem;
    } else {
      throw Exception('Failed to get response');
    }
  }

  Future<List<NewsItem>> getCachedPromptResponses() async {
    return await dbHelper.getPromptResponses();
  }
}